What features and parameters dictate electric car demand?

In [27]:
import warnings
warnings.filterwarnings('ignore')
import numpy as np
import pandas as pd
from pathlib import Path
from collections import Counter
from sklearn.metrics import balanced_accuracy_score
from sklearn.metrics import confusion_matrix
from imblearn.metrics import classification_report_imbalanced
from sklearn.model_selection import train_test_split
import psycopg2
import sqlalchemy
from sklearn.preprocessing import StandardScaler

In [28]:
# # Loading Data

connection = psycopg2.connect(
    host = 'teamev.c5ap8dqhexya.us-east-1.rds.amazonaws.com',
    port = 5432,
    user = 'postgres',
    password = 'dogecoin',
    database='postgres'
    )
cursor=connection.cursor()

sql = """
SELECT * FROM maclea; 
"""

df = pd.read_sql(sql, con=connection)
df.head(10)

,month,total_ev,elec_price,gas_price,model_id_count,brand_id_count,ev_stations,elecv_totals,hybrid_totals
0,2012-01-01,1257.0,0.128,3.380,4,4,2057.0,652.0,605.0
1,2012-02-01,1566.0,0.128,3.579,4,4,2130.0,522.0,1044.0
2,2012-03-01,3815.0,0.127,3.852,4,4,2213.0,635.0,3180.0
3,2012-04-01,3565.0,0.127,3.900,4,4,2273.0,449.0,3116.0
4,2012-05-01,3367.0,0.129,3.732,5,5,2367.0,595.0,2772.0
5,2012-06-01,2524.0,0.135,3.539,6,6,2439.0,580.0,1944.0
6,2012-07-01,3029.0,0.133,3.439,7,7,2497.0,454.0,2575.0
7,2012-08-01,4686.0,0.133,3.722,7,7,2550.0,774.0,3912.0
8,2012-09-01,5745.0,0.133,3.849,8,7,2576.0,1183.0,4562.0
9,2012-10-01,7084.0,0.128,3.746,9,7,2771.0,1972.0,5112.0

In [29]:
df2 = df.drop(columns=['month', 'elecv_totals', 'hybrid_totals'])
df2

,total_ev,elec_price,gas_price,model_id_count,brand_id_count,ev_stations
0,1257.0,0.128,3.380,4,4,2057.0
1,1566.0,0.128,3.579,4,4,2130.0
2,3815.0,0.127,3.852,4,4,2213.0
3,3565.0,0.127,3.900,4,4,2273.0
4,3367.0,0.129,3.732,5,5,2367.0
...,...,...,...,...,...,...
91,26455.0,0.139,2.621,40,22,15982.0
92,31833.0,0.139,2.592,39,22,16600.0
93,8665.0,0.136,2.627,32,16,16926.0
94,10180.0,0.133,2.598,30,15,17280.0
95,9170.0,0.133,2.555,31,15,17645.0

In [30]:
# Creating the scaler instance
data_scaler = StandardScaler()

In [31]:
# Fitting the scaler
scaled_array = data_scaler.fit_transform(df2)
scaled_array

array([[-1.35233351e+00, -1.77305924e+00,  9.34723090e-01,
        -1.82124544e+00, -2.06186065e+00, -1.24223914e+00],
       [-1.31988635e+00, -1.77305924e+00,  1.28571275e+00,
        -1.82124544e+00, -2.06186065e+00, -1.22530363e+00],
       [-1.08372565e+00, -2.01587478e+00,  1.76722118e+00,
        -1.82124544e+00, -2.06186065e+00, -1.20604819e+00],
       [-1.10997740e+00, -2.01587478e+00,  1.85188200e+00,
        -1.82124544e+00, -2.06186065e+00, -1.19212860e+00],
       [-1.13076878e+00, -1.53024371e+00,  1.55556912e+00,
        -1.73285335e+00, -1.86799324e+00, -1.17032124e+00],
       [-1.21928966e+00, -7.33505251e-02,  1.21516206e+00,
        -1.64446125e+00, -1.67412584e+00, -1.15361772e+00],
       [-1.16626114e+00, -5.58981588e-01,  1.03878535e+00,
        -1.55606916e+00, -1.48025843e+00, -1.14016212e+00],
       [-9.92264569e-01, -5.58981588e-01,  1.53793145e+00,
        -1.55606916e+00, -1.48025843e+00, -1.12786648e+00],
       [-8.81062176e-01, -5.58981588e-01,  1.76192988e+00,
        -1.46767707e+00, -1.48025843e+00, -1.12183465e+00],
       [-7.40457827e-01, -1.77305924e+00,  1.58026186e+00,
        -1.37928497e+00, -1.48025843e+00, -1.07659597e+00],
       [-8.38009313e-01, -2.01587478e+00,  1.06171432e+00,
        -1.37928497e+00, -1.48025843e+00, -1.06569229e+00],
       [-5.86097563e-01, -2.01587478e+00,  8.11259391e-01,
        -1.37928497e+00, -1.48025843e+00, -1.05316466e+00],
       [-1.00371033e+00, -1.53024371e+00,  8.27133295e-01,
        -1.20250078e+00, -1.28639102e+00, -1.04017304e+00],
       [-9.16869556e-01, -1.53024371e+00,  1.44621556e+00,
        -1.20250078e+00, -1.48025843e+00, -1.02880537e+00],
       [-6.46161557e-01, -1.77305924e+00,  1.51853001e+00,
        -1.20250078e+00, -1.48025843e+00, -1.01349382e+00],
       [-7.34787450e-01, -1.77305924e+00,  1.26983885e+00,
        -1.20250078e+00, -1.48025843e+00, -9.99574223e-01],
       [-7.01605243e-01, -1.04461265e+00,  1.34920837e+00,
        -1.11410869e+00, -1.28639102e+00, -9.93310406e-01],
       [-6.13609393e-01,  4.12280538e-01,  1.36860980e+00,
        -1.02571659e+00, -1.28639102e+00, -9.71967029e-01],
       [-7.08115676e-01,  4.12280538e-01,  1.30687796e+00,
        -9.37324500e-01, -1.09252362e+00, -9.60831355e-01],
       [-3.00583580e-01,  4.12280538e-01,  1.27689391e+00,
        -9.37324500e-01, -1.09252362e+00, -9.48303720e-01],
       [-5.46929959e-01,  4.12280538e-01,  1.20281569e+00,
        -9.37324500e-01, -1.09252362e+00, -9.37632032e-01],
       [-4.28482083e-01, -8.01797119e-01,  8.71227473e-01,
        -8.48932405e-01, -8.98656208e-01, -9.24408418e-01],
       [-5.38949428e-01, -1.28742818e+00,  6.93086993e-01,
        -8.48932405e-01, -8.98656208e-01, -9.09096865e-01],
       [-4.33207398e-01, -1.04461265e+00,  7.51291308e-01,
        -7.60540311e-01, -7.04788802e-01, -8.94481292e-01],
       [-8.94188048e-01, -3.16166056e-01,  8.16550692e-01,
        -7.60540311e-01, -7.04788802e-01, -8.68498051e-01],
       [-7.50958525e-01, -3.16166056e-01,  8.92392679e-01,
        -7.60540311e-01, -7.04788802e-01, -8.52490519e-01],
       [-4.71639953e-01, -7.33505251e-02,  1.20457946e+00,
        -7.60540311e-01, -7.04788802e-01, -8.41586837e-01],
       [-5.51550266e-01, -1.04461265e+00,  1.43034165e+00,
        -7.60540311e-01, -7.04788802e-01, -8.26739271e-01],
       [-1.86230976e-01,  1.69465006e-01,  1.45150686e+00,
        -6.72148217e-01, -5.10921395e-01, -8.13747650e-01],
       [-2.17628064e-01,  1.86917373e+00,  1.48501844e+00,
        -6.72148217e-01, -5.10921395e-01, -7.94724206e-01],
       [-3.03838796e-01,  1.86917373e+00,  1.34215330e+00,
        -5.83756123e-01, -3.17053988e-01, -7.78252687e-01],
       [-2.06182303e-01,  1.86917373e+00,  1.12344617e+00,
        -4.95364028e-01, -3.17053988e-01, -7.52269446e-01],
       [-3.37546037e-01,  1.38354266e+00,  9.80581036e-01,
        -4.95364028e-01, -3.17053988e-01, -7.27678164e-01],
       [-4.61664290e-01,  1.69465006e-01,  5.66095759e-01,
        -3.18579840e-01,  7.06808254e-02, -7.11206645e-01],
       [-4.71429939e-01, -3.16166056e-01,  1.09280072e-01,
        -2.30187746e-01,  7.06808254e-02, -6.95431106e-01],
       [-1.15246256e-01, -7.33505251e-02, -5.41550000e-01,
        -2.30187746e-01,  7.06808254e-02, -6.78263607e-01],
       [-8.50085116e-01,  6.55096069e-01, -1.29467857e+00,
        -3.18579840e-01,  7.06808254e-02, -6.48800468e-01],
       [-7.54633769e-01,  6.55096069e-01, -1.11830185e+00,
        -3.18579840e-01,  7.06808254e-02, -6.33024928e-01],
       [-3.98975122e-01,  1.69465006e-01, -6.80887604e-01,
        -3.18579840e-01,  7.06808254e-02, -6.07969660e-01],
       [-5.29813821e-01,  4.12280538e-01, -6.72068768e-01,
        -3.18579840e-01,  7.06808254e-02, -5.62498988e-01],
       [-2.72966743e-01,  4.12280538e-01, -2.32890752e-01,
        -3.18579840e-01,  7.06808254e-02, -5.30019937e-01],
       [-3.96034926e-01,  1.86917373e+00, -8.47343127e-02,
        -3.18579840e-01,  7.06808254e-02, -4.95916933e-01],
       [-5.44409792e-01,  1.62635819e+00, -9.88444498e-02,
        -2.30187746e-01,  7.06808254e-02, -4.69469705e-01],
       [-5.42204645e-01,  1.62635819e+00, -3.77519657e-01,
        -1.41795651e-01,  2.64548232e-01, -4.33510755e-01],
       [-4.20186532e-01,  1.38354266e+00, -8.55500550e-01,
        -2.30187746e-01, -1.23186581e-01, -4.09151467e-01],
       [-4.42237998e-01,  1.69465006e-01, -9.87783085e-01,
        -1.41795651e-01,  7.06808254e-02, -3.40713466e-01],
       [-4.26906979e-01, -3.16166056e-01, -1.22060035e+00,
         1.23380632e-01,  4.58415639e-01, -3.01970597e-01],
       [-4.58366414e-02, -5.58981588e-01, -1.43225240e+00,
         1.23380632e-01,  6.52283046e-01, -2.62995736e-01],
       [-8.32128922e-01, -3.16166056e-01, -1.58922768e+00,
        -5.34035570e-02,  2.64548232e-01, -1.93165775e-01],
       [-6.69788128e-01, -3.16166056e-01, -1.91552460e+00,
        -5.34035570e-02,  2.64548232e-01, -1.33079530e-01],
       [-3.00855941e-02, -3.16166056e-01, -1.55395233e+00,
         3.49885373e-02,  2.64548232e-01, -8.76088580e-02],
       [-3.78918788e-01, -3.16166056e-01, -1.29996987e+00,
         3.49885373e-02,  2.64548232e-01, -5.39698404e-02],
       [-2.80632253e-01, -5.58981588e-01, -1.02658596e+00,
         3.49885373e-02,  2.64548232e-01, -1.26750465e-02],
       [ 7.52364087e-02,  6.55096069e-01, -8.53736783e-01,
         1.23380632e-01,  2.64548232e-01,  1.79480591e-02],
       [-1.12621082e-01,  8.97911600e-01, -1.07773521e+00,
         1.23380632e-01,  2.64548232e-01,  5.29790360e-02],
       [ 4.77245795e-02,  8.97911600e-01, -1.18532500e+00,
         1.23380632e-01,  2.64548232e-01,  1.01465620e-01],
       [ 3.23892942e-01,  8.97911600e-01, -1.11301055e+00,
         1.23380632e-01,  2.64548232e-01,  1.35336631e-01],
       [-3.28515437e-01, -3.16166056e-01, -1.06009754e+00,
         1.23380632e-01,  2.64548232e-01,  1.62015851e-01],
       [-9.43498671e-02, -1.04461265e+00, -1.17826994e+00,
         2.11772726e-01,  4.58415639e-01,  1.91710984e-01],
       [ 1.11827076e+00, -5.58981588e-01, -1.05127870e+00,
         4.76949009e-01,  4.58415639e-01,  2.41125541e-01],
       [-3.28725451e-01, -3.16166056e-01, -8.83720824e-01,
         6.53733197e-01,  6.52283046e-01,  2.78940437e-01],
       [-1.84655872e-01, -7.33505251e-02, -9.63090345e-01,
         4.76949009e-01,  2.64548232e-01,  3.06547630e-01],
       [ 4.62607165e-01, -3.16166056e-01, -9.26051235e-01,
         6.53733197e-01,  4.58415639e-01,  3.68721814e-01],
       [-8.09089734e-02, -7.33505251e-02, -7.63784659e-01,
         8.30517386e-01,  4.58415639e-01,  3.90529177e-01],
       [ 2.58368585e-01,  4.12280538e-01, -8.09642604e-01,
         6.53733197e-01,  4.58415639e-01,  4.17208398e-01],
       [ 3.05621727e-01,  1.62635819e+00, -8.87248358e-01,
         7.42125292e-01,  6.52283046e-01,  4.38783768e-01],
       [ 1.47481212e-01,  1.86917373e+00, -9.70145414e-01,
         1.00730157e+00,  6.52283046e-01,  4.64767009e-01],
       [ 2.49758013e-01,  1.62635819e+00, -8.29044043e-01,
         1.09569367e+00,  8.46150452e-01,  4.84486433e-01],
       [ 7.46231023e-01,  1.62635819e+00, -3.61645753e-01,
         1.09569367e+00,  8.46150452e-01,  6.35746016e-01],
       [ 1.88476594e-02,  4.12280538e-01, -6.08573151e-01,
         1.09569367e+00,  8.46150452e-01,  6.59873311e-01],
       [ 3.18117558e-01,  1.69465006e-01, -5.04510890e-01,
         1.18408576e+00,  8.46150452e-01,  6.88408478e-01],
       [ 1.16279372e+00,  1.69465006e-01, -6.57958631e-01,
         1.18408576e+00,  1.04001786e+00,  7.09751854e-01],
       [-2.44509851e-01, -7.33505251e-02, -5.20384795e-01,
         1.27247786e+00,  1.04001786e+00,  7.33879150e-01],
       [ 2.76429786e-01, -7.33505251e-02, -4.63944246e-01,
         1.36086995e+00,  1.04001786e+00,  7.40606953e-01],
       [ 1.28103158e+00, -7.33505251e-02, -4.56889178e-01,
         1.36086995e+00,  1.04001786e+00,  7.76101916e-01],
       [ 5.71394398e-01, -3.16166056e-01, -1.64103834e-01,
         1.36086995e+00,  1.04001786e+00,  8.15772758e-01],
       [ 1.06114696e+00,  1.69465006e-01,  8.98786335e-02,
         1.36086995e+00,  1.04001786e+00,  8.40132046e-01],
       [ 1.12992653e+00,  8.97911600e-01,  7.22409622e-02,
         1.27247786e+00,  1.04001786e+00,  8.90010590e-01],
       [ 1.60928341e+00,  8.97911600e-01, -1.83725743e-03,
         1.27247786e+00,  1.04001786e+00,  9.51256801e-01],
       [ 2.32228081e+00,  8.97911600e-01, -2.47662302e-02,
         1.36086995e+00,  1.04001786e+00,  9.89071696e-01],
       [ 3.18050288e+00,  6.55096069e-01, -2.47662302e-02,
         1.27247786e+00,  1.04001786e+00,  1.03268642e+00],
       [ 2.08034473e+00,  1.69465006e-01,  1.75641810e-02,
         1.27247786e+00,  1.23388527e+00,  1.08256497e+00],
       [ 2.97983454e+00, -3.16166056e-01, -3.58118218e-01,
         1.18408576e+00,  1.23388527e+00,  1.32198197e+00],
       [ 3.74281527e+00, -7.33505251e-02, -8.53736783e-01,
         1.27247786e+00,  1.23388527e+00,  1.37325248e+00],
       [ 1.82973572e-01, -7.33505251e-02, -1.06186130e+00,
         1.09569367e+00,  1.23388527e+00,  1.42521896e+00],
       [ 2.13215583e-01,  1.69465006e-01, -9.54271509e-01,
         1.36086995e+00,  1.42775267e+00,  1.48808912e+00],
       [ 1.16646896e+00, -7.33505251e-02, -5.89171713e-01,
         1.27247786e+00,  1.42775267e+00,  1.58019043e+00],
       [ 6.46579397e-01, -7.33505251e-02, -9.17893812e-02,
         1.36086995e+00,  1.42775267e+00,  1.68922725e+00],
       [ 1.36125692e+00,  1.69465006e-01,  1.58004139e-02,
         1.09569367e+00,  1.23388527e+00,  1.77088886e+00],
       [ 2.28594840e+00,  8.97911600e-01, -2.36418286e-01,
         1.27247786e+00,  1.42775267e+00,  1.81241565e+00],
       [ 1.18421514e+00,  1.14072713e+00, -1.94087875e-01,
         1.36086995e+00,  1.42775267e+00,  1.86415014e+00],
       [ 1.29363242e+00,  8.97911600e-01, -4.03976164e-01,
         1.36086995e+00,  1.42775267e+00,  1.98826651e+00],
       [ 1.85835997e+00,  8.97911600e-01, -4.55125411e-01,
         1.27247786e+00,  1.42775267e+00,  2.13163833e+00],
       [-5.74441788e-01,  1.69465006e-01, -3.93393561e-01,
         6.53733197e-01,  2.64548232e-01,  2.20726812e+00],
       [-4.15356211e-01, -5.58981588e-01, -4.44542808e-01,
         4.76949009e-01,  7.06808254e-02,  2.28939372e+00],
       [-5.21413262e-01, -5.58981588e-01, -5.20384795e-01,
         5.65341103e-01,  7.06808254e-02,  2.37407125e+00]])

In [32]:
# Convert the array to a dataframce with scaled values
df_scaled = pd.DataFrame(scaled_array,columns=['total_ev', 'elec_price', 'gas_price', 'model_id_count', 'brand_id_count', 'ev_stations'])
df_scaled

,total_ev,elec_price,gas_price,model_id_count,brand_id_count,ev_stations
0,-1.352334,-1.773059,0.934723,-1.821245,-2.061861,-1.242239
1,-1.319886,-1.773059,1.285713,-1.821245,-2.061861,-1.225304
2,-1.083726,-2.015875,1.767221,-1.821245,-2.061861,-1.206048
3,-1.109977,-2.015875,1.851882,-1.821245,-2.061861,-1.192129
4,-1.130769,-1.530244,1.555569,-1.732853,-1.867993,-1.170321
...,...,...,...,...,...,...
91,1.293632,0.897912,-0.403976,1.360870,1.427753,1.988267
92,1.858360,0.897912,-0.455125,1.272478,1.427753,2.131638
93,-0.574442,0.169465,-0.393394,0.653733,0.264548,2.207268
94,-0.415356,-0.558982,-0.444543,0.476949,0.070681,2.289394
95,-0.521413,-0.558982,-0.520385,0.565341,0.070681,2.374071

In [33]:
num_corr_col = [col for col in df_scaled.columns if df_scaled[col].dtype == 'int64' or df_scaled[col].dtype == 'float64']
corr_dict = {}
#Getting absolute values of correlation since we would need to inspect negative correlation too
for col in num_corr_col:
    corr_dict[col] = abs(df_scaled[col].corr(df_scaled['total_ev']))

In [34]:
for w in sorted(corr_dict, key=corr_dict.get):
    print(w, corr_dict[w])

gas_price 0.3456399598024233
elec_price 0.3570816055619479
ev_stations 0.711506989843572
brand_id_count 0.7489882500777195
model_id_count 0.7760864133115364
total_ev 1.0